In [13]:
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
import numpy as np

# Making two lists of 5 elements each from the user.
li1 = []
li2 = []
for i in range(5):
    a = input()
    b = li1.append(a)
print(li1)
for i in range(5):
    a = input()
    b = li2.append(a)
print(li2)

# Converting list into numpy arrays
print('Numpy Arrays')
nparr1 = np.array(li1)
print(nparr1)
nparr2 = np.array(li2)
print(nparr2)

# Concatenating arrays
print('Concatenating arrays')
con = np.concatenate((nparr1,nparr2))  
print(con)

# sorting arrays
print('sorted arrays')
nparr1.sort()
print(nparr1)
nparr2.sort()
print(nparr2)

65
78
44
78
65
['65', '78', '44', '78', '65']
45
22
67
87
90
['45', '22', '67', '87', '90']
Numpy Arrays
['65' '78' '44' '78' '65']
['45' '22' '67' '87' '90']
Concatenating arrays
['65' '78' '44' '78' '65' '45' '22' '67' '87' '90']
sorted arrays
['44' '65' '65' '78' '78']
['22' '45' '67' '87' '90']


In [23]:
import numpy as np

a_1d = np.arange(3)
print(a_1d)

print(a_1d.shape)

a_2d = np.arange(12).reshape((3, 4))
print(a_2d)

print(a_2d.shape)

[0 1 2]
(3,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [17]:
x1 = np.arange(4)
print("row vector:", x1[np.newaxis, :] )
print(x1[np.newaxis, :].shape)
x2 = np.arange(12).reshape((3, 4))

print("column vector:\n", x2)
print(x2[:, np.newaxis].shape)
print("column vector:\n", x1[:, np.newaxis])
print(x1[:, np.newaxis].shape)

row vector: [[0 1 2 3]]
(1, 4)
column vector:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 1, 4)
column vector:
 [[0]
 [1]
 [2]
 [3]]
(4, 1)


In [21]:
print("Row vector using expand_dims:",np.expand_dims(x1, axis=0)) 
print("column vector using expand_dims:\n", np.expand_dims(x1, axis=1))

print("Row vector using expand_dims:\n",np.expand_dims(x2, axis=0)) 

Row vector using expand_dims: [[0 1 2 3]]
column vector using expand_dims:
 [[0]
 [1]
 [2]
 [3]]
Row vector using expand_dims:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
